### ISSUE TITLE
Didn't work with light mode in 22622.290

### ISSUE THREAD

**Issue by HuyHung1408** [krlvm/AccentColorizer-E11#1]
It used to work with older builds. For now, reapplying it does nothing except the display setting icon. I did check `C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard\theme-light` too
![image](https://user-images.githubusercontent.com/86362423/177459903-d5aa828e-d9b0-413a-bb1b-e67d5019b3a6.png)
![image](https://user-images.githubusercontent.com/86362423/177459945-ee36f8f0-d302-49fb-9567-037615b6f789.png)

**Comment by HuyHung1408** [comment]
Alright I checked, AccentColorizer-E11 works with dark mode, light mode didn't get patch

**Comment by krlvm** [comment]
Can you send contents of `C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard`?

**Comment by krlvm** [comment]
I guess after the update the original icons has been restored and it led to inconsistent state. Navigate to `HKCU\SOFTWARE\AccentColorizer` key and set `light` value to `#0078D4`, then run it again.

**Comment by HuyHung1408** [comment]
It works! Thanks for fix, I got to say that your work was great!
