### ISSUE TITLE
Issue with StartAllBack + Dark Mode - Windows 11

### ISSUE THREAD

**Issue by aidonaks** [krlvm/AccentColorizer-E11#11]
This utility works great, thanks for making it!

I want to report one conflict this has with StartAllBack version 3.5.7 + Dark mode in Windows 11 (22H2 22621.963).

Some menus in the start menu have their background also changed to the system accent color, which doesn't work well with dark mode and a light accent color, as you can see.

![startallback](https://user-images.githubusercontent.com/29076196/210183396-91767949-f2fb-4209-aaad-de4579375aaf.png)

**Comment by krlvm** [comment]
Um, what does AccentColorizer-E11 have to do with it? :/

**Comment by aidonaks** [comment]
> Um, what does AccentColorizer-E11 have to do with it? :/

That light background on the control panel sub menu that you see is after running AccentColorizer-E11. Otherwise that sub menu background is in perfectly readable regular dark mode.

**Comment by krlvm** [comment]
It has nothing to do with it, this program just patches files in `C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard`
