### ISSUE TITLE
Glyph icons not changing colors after changing Accent color.

### ISSUE THREAD

**Issue by Vipin2003** [krlvm/AccentColorizer-E11#12]
Hello krlvm, the glyph icons are not changing colors with the accent colors. It only changes color if we reinstall the app. But after that, not working. And also, there is no effect of SAB on the app. The glyph icons of SAB (ribbon ui) changing color but not the win11 command bar glyph icons not changing color. Please check this issue. I think that it is the same issue as I posted in AccentColorizer Issue page.

https://user-images.githubusercontent.com/93650504/226369361-d8a9c43c-89c8-4043-b505-a2ef0a05f89a.mp4

**Comment by krlvm** [comment]
Can you check colors in `C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard\theme-*`?

**Comment by Vipin2003** [comment]
i've reinstalled it by mistake and working fine...if happens again then i will msg here.

**Comment by Vipin2003** [comment]
Ya...there is a bug in this. After few days after reinstalling, it get stops workking. I tried this on a fresh installed Win11 too, but the result is same.

**Comment by Vipin2003** [comment]
But there is only edge icon on every glyph icon i can see...any solution of that

**Comment by krlvm** [comment]
Those are SVGs. Just double click on them.

**Comment by Vipin2003** [comment]
Nope...they are not changing colors

**Comment by krlvm** [comment]
What if you restart AccentColorizer?

**Comment by Vipin2003** [comment]
the problem get solved...but after 1-2 days, the problem gets started again.

**Comment by Vipin2003** [comment]
is there any plan to fix this bug ??

**Comment by krlvm** [comment]
I don't have a Windows 11 installation at the moment

**Comment by IdkWhatToCallMe123** [comment]
coming in here to say that after using this program for only one time it doesn't work after that
