### ISSUE TITLE
Explorer.exe crashes when I use the Alt+Tab keyboard shortcut

### ISSUE THREAD

**Issue by Valer100** [krlvm/AccentColorizer-E11#13]
I used this tool for colorizing the Explorer's icons with the Windows's accent color. After using this tool, every time I use Alt+Tab, I cannot switch apps by using that shortcut and after a few seconds, the explorer crashes. My Windows 11 version is 22H2 build 22621.1105

**Comment by krlvm** [comment]
This tool just edits SVG files, it doesn't interfere with AltTab in any way
