### ISSUE TITLE
The color of the glyphs doesn't change in the new file explorer version Windows App SDK of Windows 11 Dev channel.

### ISSUE THREAD

**Issue by Dhyfer1** [krlvm/AccentColorizer-E11#14]
Hi @krlvm 

As the title says. I'm using Windows 11 channel Dev (latest compilation 23440.1000) and the glyphs don't change color, well, they do change but only the ones in the path. `C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard`

But this path where the glyphs are located is not used by the Windows file explorer, because the mentioned path is where the glyphs are located in the Windows 11 Insider Beta channel. In Windows 11 Dev channel, the new path where the glyphs are found is `C:\Windows\SystemApps\MicrosoftWindows.Client.FileExp_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard`, as you can see in the picture.

![Screenshot 2023-04-21 225954](https://user-images.githubusercontent.com/50301201/233815303-81205763-bd1e-43a1-9a19-d8af1be8709a.png)

As I said before, only the glyphs in the first path do change color (In Windows 11 Dev there are both routes), but those glyphs are not applied to the file explorer. In the Dev channel, the file explorer uses the glyphs found in the second path, and these glyphs do not change color.

So the path where the glyphs are located is different depending on the version of Windows 11 (Canary, Dev, Beta, Preview or Stable)

Please can you update AC-E11 to work on Windows 11 Dev?
Thanks in advance

**Comment by krlvm** [comment]
Thanks for providing paths, it's available in [v1.1.2](https://github.com/krlvm/AccentColorizer-E11/releases/tag/v1.1.2) now

**Comment by Dhyfer1** [comment]
Thank you very much for the update. Works as expected. It does color the glyphs now, and also the Windows Spotlight glyphs as I mentioned in a previous comment.

I have found out that the first path I mentioned before contains the glyphs for the stable, beta and release preview versions of Windows 11. And the second path contains the glyphs for the dev and canary channels.

By the way, I was looking at the screenshots of this repository and I noticed that the file explorer title bar also uses a mica effect like the command bar. How did you get it? As you can see in my screenshot, I have the accent color applied to the toolbar and for that I used [MicaForEveryone](https://github.com/MicaForEveryone/MicaForEveryone), but with this tool I can't apply mica to the title bar. So how is yours so different?

**Comment by krlvm** [comment]
It was a clean 21H2 install, without any external tools

**Comment by Dhyfer1** [comment]
Uh, can you tell me how to do it? 🤔

**Comment by krlvm** [comment]
You can modify AccentColorizer installation script or add a key to `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`

**Comment by Dhyfer1** [comment]
That's fine, thanks. I don't use any script for AC-E11, I had just placed the executable in the shell:startup folder. But I'll try adding a key to the registry as you mention. 

Thank you.
