### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by odopo** [krlvm/AccentColorizer-E11#15]
AccentColorizer-E11 is crashing after updating to newest canary Windows 11 build 25352.1. It is now a new branch zn_release and some features are said to be missing from previous build. I had Windows App SDK version of Windows Explorer in previous builds. I noticed that it has reverted to normal version for me in latest build. AccentColorizer-E11 v1.1.2.0 was working for me on previous build but is crashing on Windows 11 Home Insider Preview Single Language Build 25352.zn_release.230422-2250. I have added crash events from Event Viewer below and attached the Report.wer file. Please look into it if possible.

Log Name:      Application
Source:        Application Error
Date:          29-04-2023 09:33:50 PM
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      

Description:
Faulting application name: AccentColorizer-E11.exe, version: 1.1.2.0, time stamp: 0xb06da25e
Faulting module name: KERNELBASE.dll, version: 10.0.25352.1, time stamp: 0x8f2afbe7
Exception code: 0xe0434352
Fault offset: 0x000000000003404c
Faulting process ID: 0x0x13C0
Faulting application start time: 0x0x1D97AB430400DD7
Faulting application path: C:\Portable\AccentColorizer-E11\AccentColorizer-E11.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 02c3e85e-ff2d-46c1-953b-5c2e01da7c69
Faulting package full name: 
Faulting package-relative application ID: 

--------------------------------------------------------------------------------------------------------------------------------------------

Log Name:      Application
Source:        .NET Runtime
Date:          29-04-2023 09:33:50 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A

Description:
Application: AccentColorizer-E11.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CommonInit()
   at System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.String, System.String, System.String, System.IO.SearchOption, System.IO.SearchResultHandler`1<System.__Canon>, Boolean)
   at System.IO.DirectoryInfo.InternalGetFiles(System.String, System.IO.SearchOption)
   at AccentColorizer_E11.GlyphColorizer.ColorizeGlyphs(System.String, System.Windows.Media.Color, System.String)
   at AccentColorizer_E11.GlyphColorizer.ApplyColorization()
   at AccentColorizer_E11.AccentColorListener.ApplyColorization()
   at AccentColorizer_E11.Program.Main(System.String[])

--------------------------------------------------------------------------------------------------------------------------------------------

[Report.wer.txt](https://github.com/krlvm/AccentColorizer-E11/files/11359608/Report.wer.txt)

**Comment by krlvm** [comment]
Can you check your `C:\Windows\SystemApps\MicrosoftWindows.Client.FileExp_cw5n1h2txyewy\` directory?

Does `C:\Windows\SystemApps\MicrosoftWindows.Client.FileExp_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard\theme-light` exist?

**Comment by odopo** [comment]
> Can you check your `C:\Windows\SystemApps\MicrosoftWindows.Client.FileExp_cw5n1h2txyewy\` directory?
> 
> Does `C:\Windows\SystemApps\MicrosoftWindows.Client.FileExp_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard\theme-light` exist?

No, there isn't even a **FileExplorerExtensions** folder at that location. 

![image](https://user-images.githubusercontent.com/100270166/235355213-15e460c6-4317-4ae7-82c2-b51230af0da2.png)

The Assets folder also only has these 6 files.

![image](https://user-images.githubusercontent.com/100270166/235355309-a37f50d6-3193-44c0-aba1-fbebd01c2f97.png)

**Comment by krlvm** [comment]
Well, I think they moved those icons to another place, do you have anything in `C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard\theme-light` though?

**Comment by odopo** [comment]
> 

Yes, the icons exist at that location.

![image](https://user-images.githubusercontent.com/100270166/235369703-be888fcd-9b62-406e-b49b-6c25a1c71b90.png)

**Comment by krlvm** [comment]
I think you can use the previous version until Microsoft move the assets back
