### ISSUE TITLE
The app not running in Background process

### ISSUE THREAD

**Issue by lazuee** [krlvm/AccentColorizer-E11#16]
After running the app, it didn't run on background process. But, it still changing the accent color of the icon glyphs. 
I'm just wondering why it doesn't running in background process. I manually run the app, not with `-Apply` argument.

**Comment by krlvm** [comment]
Do you have any errors in event viewer?

**Comment by lazuee** [comment]
It's now running in background process after restarting,..
Hmmm.. weird before I restart my laptop, it doesn't run at background process at all, when I run the app many times.
