### ISSUE TITLE
Doesn't work on Windows 22621.2070

### ISSUE THREAD

**Issue by Youseffo13** [krlvm/AccentColorizer-E11#19]
since I have upgraded to windows 22621.2070 accent colorizer-E11 does not work.

**Comment by krlvm** [comment]
What version of the program are you using?

**Comment by GGsource** [comment]
Can confirm, I downloaded AccentColorizer-E11 only 3 days ago (so its the most recent version) and updating to 22621.2070 broke it sadly.

**Comment by duckduckdog** [comment]
Still working on 22621.2115 thankfully.

**Comment by krlvm** [comment]
I'll download 22621.2070 and check today

**Comment by Youseffo13** [comment]
> What version of the program are you using?

I use version 1.1.2

**Comment by krlvm** [comment]
Looks like `MicrosoftWindows.Client.FileExp_cw5n1h2txyewy` is installed even if WASDK File Explorer (new, laggy File Explorer with refreshed UI) is not enabled for you (A/B testing), so:

- If you **have** WASDK File Explorer, use [version 1.1.2](https://github.com/krlvm/AccentColorizer-E11/releases/tag/v1.1.2)
- If you **don't have** WASDK File Explorer, use [version 1.1.1](https://github.com/krlvm/AccentColorizer-E11/releases/tag/v1.1.1)

**Comment by krlvm** [comment]
If anyone knows how to determine if WASDK File Explorer is enabled, please let me know

**Comment by Youseffo13** [comment]
> Looks like `MicrosoftWindows.Client.FileExp_cw5n1h2txyewy` is installed even if WASDK File Explorer (new, laggy File Explorer with refreshed UI) is not enabled for you (A/B testing), so:
> 
> * If you **have** WASDK File Explorer, use [version 1.1.2](https://github.com/krlvm/AccentColorizer-E11/releases/tag/v1.1.2)
> * If you **don't have** WASDK File Explorer, use [version 1.1.1](https://github.com/krlvm/AccentColorizer-E11/releases/tag/v1.1.1)

I have tried both versions but neither works

**Comment by Youseffo13** [comment]
the image are located at this path C:\Windows\SystemApps\MicrosoftWindows.Client.FileExp_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard\theme-dark

**Comment by krlvm** [comment]
How does your Explorer look like (is the toolbar below the address bar)?
Try killing ACE-11 process and restarting lastest version as administrator.

**Comment by Youseffo13** [comment]
> How does your Explorer look like (is the toolbar below the address bar)? Try killing ACE-11 process and restarting lastest version as administrator.

I tried it but it doesn't work anyway this is what file explorer looks like 
![image](https://github.com/krlvm/AccentColorizer-E11/assets/110458691/48ce664a-b7d8-4cf4-a0ff-bf0c559d8365)

**Comment by krlvm** [comment]
You should run [version 1.1.1](https://github.com/krlvm/AccentColorizer-E11/releases/tag/v1.1.1) as administrator

**Comment by Youseffo13** [comment]
> You should run [version 1.1.1](https://github.com/krlvm/AccentColorizer-E11/releases/tag/v1.1.1) as administrator as it is not WASDK Explorer

doesn't work

**Comment by bancalero** [comment]
updated to version 22621.2070 3 days ago and can confirm that none of the releases work anymore :(

**Comment by krlvm** [comment]
I just installed .2070 one more time in the VM and everything works with the latest version/WASDK Explorer.

Check if SVG colors have changed in directories `C:\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard\theme-?` or `C:\SystemApps\MicrosoftWindows.Client.FileExp_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard\theme-?`

**Comment by bancalero** [comment]
Nothing changes. The app doesn’t work at all. Tried every single version available here and none works

**Comment by alpcinar** [comment]
> Check if SVG colors have changed in directories

I'm on version 22621.2070 with AccentColorizer-E11 v1.1.2 installed.

`C:\Windows\SystemApps\MicrosoftWindows.Client.FileExp_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard` colors change accordingly
`C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard` colors don't change

**Comment by krlvm** [comment]
This experimental build should work as it colorizes SVGs in all known directories

[AccentColorizer-E11.zip](https://github.com/krlvm/AccentColorizer-E11/files/12250326/AccentColorizer-E11.zip)

**Comment by alpcinar** [comment]
Can confirm the build above is working for me, thanks for the quick work.

**Comment by krlvm** [comment]
Fix is released in [version 1.2.0](https://github.com/krlvm/AccentColorizer-E11/releases/tag/v1.2.0)

**Comment by bancalero** [comment]
Just to confirm that now everything is working normally. Thank you for the quick fix!

**Comment by duckduckdog** [comment]
Thank you!
I'm always amazed when free software offers better support & communication than paid software. I can't find a donation link anywhere, is there a project I could donate to in your honor?

**Comment by krlvm** [comment]
> Thank you! I'm always amazed when free software offers better support & communication than paid software. I can't find a donation link anywhere, is there a project I could donate to in your honor?

Thanks for the kind words, much appreciated. As for donations, not yet, but it's very nice to hear that someone is using and appreciating the updates.
