### ISSUE TITLE
How to uninstall or revert changes?

### ISSUE THREAD

**Issue by Dhyfer1** [krlvm/AccentColorizer-E11#2]
Hi @krlvm 

I have downloaded the latest version and I want the glyphs to recover the default color they had before I used AccentColorizer-E11 for the first time.

In the readme file of this repository there aren't any instructions for installing/uninstalling/reverting changes etc. Instructions are needed, the exe file doesn't open a command console, and it doesn't even have a user interface.

Also, after running the exe file, I see that AccentColorizer-E11 also changed the color of all the images inside the theme-dark and theme-light folders located at `C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard` to the selected accent color.

What can I do about it to undo the changes made by AccentColorizer-E11 and have the glyphs as they were before? I hope I don't have to reinstall Windows 11 because of this problem.

By the way, could AccentColorizer-E11 in a next version apply the accent color automatically when the accent color is set to Automatic for Windows 11?
Settings>Personalization>Colors>Accent color>Automatic

I look forward to your response. Thank you in advance

**Comment by krlvm** [comment]
In order to undo the changes, it is enough to select the blue color by default in the Windows settings, run AC once and everything will return to its place.

**Comment by krlvm** [comment]
> By the way, could AccentColorizer-E11 in a next version apply the accent color automatically when the accent color is set to Automatic for Windows 11?
Settings>Personalization>Colors>Accent color>Automatic

Accent color change monitoring implemented in [version 1.1.0](https://github.com/krlvm/AccentColorizer-E11/releases/tag/v1.1.0). It consumes much more memory that AccentColorizer though (6MB vs 1MB), maybe I will rewrite it in C++ later.

**Comment by Dhyfer1** [comment]
> In order to undo the changes, it is enough to select the blue color by default in the Windows settings, run AC once and everything will return to its place.

@krlvm It's not as simple as it sounds. The blue color is different for all the glyphs (dark theme on the left and light theme on the right) as you can see in the picture. I had to install Windows 11 on another partition to recover the glyphs with their original color, you can see that the blue color for the glyphs in the theme-light folder is darker, while the blue color for the glyphs in the theme-dark folder is lighter.

![image_7](https://user-images.githubusercontent.com/50301201/187098971-7a7e56bc-3d58-43e6-8b3b-ab33da6338c0.png)

I think you should mention in the readme that the user backup the original glyphs before using AccentColorizer-E11 in case he wants to revert the changes, or at least that AccentColorizer-E11 can create a backup.

**Comment by krlvm** [comment]
> It's not as simple as it sounds. The blue color is different for all the glyphs (dark theme on the left and light theme on the right) as you can see in the picture.

No, if you select the color named "Default Blue" in personalization settings, everything will be reset to original colors: all glyphs for light theme share the same blue color (`#0078D4`) - it is `ImmersiveSystemAccent` from the system palette, and all dark glyphs share color `#4CC2FF` which is `ImmersiveSystemAccentLight2` respectively - tested it right now.

> I had to install Windows 11 on another partition to recover the glyphs with their original color

If you need to get something from fresh Windows installation, you can open the ISO file with 7-Zip, navigate to folder `sources` and open `install.wim`/`install.esd`.

**Comment by Dhyfer1** [comment]
> No, if you select the color named "Default Blue" in personalization settings, everything will be reset to original colors

I don't see any color called "Default Blue" in the Win11 customization settings, in this image it appears as "Blue" and has the value `#0078D4`, the blue color to the right of it is called "Navy blue".

![image](https://user-images.githubusercontent.com/50301201/187201021-3cebd9e6-feaa-4646-8b00-7900a369c0ce.png)

> If you need to get something from fresh Windows installation, you can open the ISO file with 7-Zip, navigate to folder `sources` and open `install.wim`/`install.esd`.

Thank you very much for the information, I didn't know that. I used 7zip with the Win11 iso, and opened the install.wim file (F:\sources install.wim). Inside the install.wim file I found 11 folders, all with the same content, I only had to select one of those folders, folder 3 for example, to get to the glyphs path. `F:\sources\install.wim\3\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard\` I did not find the install.esd file.

**Comment by krlvm** [comment]
> I don't see any color called "Default Blue" in the Win11 personalization settings, in this image it appears as "Blue" and has the value #0078D4, the blue color to the right of it is called "Navy blue".

Yes, it is the correct color, I remember it was called "Default Blue" previously though. If you select this color, recolorize the glyphs and compare them with the original files they will be absolutely identical.

**Comment by Dhyfer1** [comment]
Hi. The new version of Accent Colorizer-E11 works well with the automatic mode for the accent color. I thought that the glyph color would automatically change to the selected accent color without closing File Explorer, but I found that I have to reopen File Explorer to see the changes. Can you add this feature in a future release? It's a minor thing, but I'd like to see immediately when the glyph color changes without having to close File Explorer, but if it's not possible to achieve this, no problem, it's just an idea.

As I said in a question in the Accent Colorizer repository, I'd like you to find a way to apply the accent color to the selected item's box when Windows is in dark mode. 

Finally, AccentColorizer-E11 starts automatically every time I start Windows?

**Comment by krlvm** [comment]
Recolorizing without reopening File Explorer is not possible because there's no way to force it to reload glyphs.

As I said previously, grey selection in dark mode is intended design choice by Microsoft to ensure there's enough contrast between black and white - if it were following the accent color, it would be unusable with particular colors due to low contrast. 

To launch ACE11 you can either modify any quick and dirty batch installer of any of my projects (AccentColorizer/MediaFlyout/TrayVolumeControl), either put the executable to Autorun directory, which is present since Windows 95 IIRC.

**Comment by Dhyfer1** [comment]
Ok, not problem.

Now I understand why there are no Windows screenshots with the file explorer in dark theme in the Accent Colorizer repository.

Thanks, the easiest route for me was to place the executable file in the Startup folder and it works without any problem.
