### ISSUE TITLE
The color of windows file explorer glyphs remain yellow while using the default W11 dark theme

### ISSUE THREAD

**Issue by krilok** [krlvm/AccentColorizer-E11#24]
Hi, Devs.

I installed AccentColorizer-11 v1.2.0 on my laptop, but couldn't get it to apply the set Windows colour to the glyphs on the default file explorer.

I did a bit of troubleshooting, and it seems that AC-11 is not applying the set colour if I'm using the default W11 dark theme. If I switch to the light theme, then AC-11 will do its job and the colour of the glyphs do indeed change. 

There was another user who had a similar issue (https://github.com/krlvm/AccentColorizer-E11/issues/10), so I followed the recommendations on that issue and checked if glyphs on the 'C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard' were being changed, and whilst on the 'theme-light' folder they were, on the 'theme-dark' they remained the same (default yellow accent).

I thought maybe I could solve this by setting the light theme first with my desired accent colour, and then just copy the contents of the 'theme-light' folder and overwrite the 'theme-dark' one, and so I did. I made a backup of the folders first just in case, and then went ahead, but unfortunately, although it worked and the glyphs had the colour I had set on the light theme, they were slightly less readable and looked a bit odd.

Besides, if in the future I would want to change accent colour again, I would have to repeat the process all over, so, is there something you could look into to correct this?

And thank you in advance...

**Comment by krlvm** [comment]
I haven't followed the current status of Windows for a long time, is the default accent in dark theme yellow now?

**Comment by krlvm** [comment]
You need to set current dark accent manually in `HKCU\Software\AccentColorizer" to yellow color from SVG files in `theme-dark` for now and it will work again without any issues

**Comment by krilok** [comment]
> I haven't followed the current status of Windows for a long time, is the default accent in dark theme yellow now?

On default dark theme, I believe the accent is blue, but the glyphs on file explorer have always showed up as yellow.

**Comment by krlvm** [comment]
> > You need to set current dark accent manually in `HKCU\Software\AccentColorizer` to yellow color from SVG files in `theme-dark` for now and it will work again without any issues
> 
> Sorry, but I didn't quite understand that. Wouldn't the glyphs remain yellow then?

ACE-11 actually just searches that SVG files for the color from the registry and replaces it to the current accent color. I.e. the color from the registry should match the color from the files. Sync it manually by modifying the registry key and it will work.

**Comment by krilok** [comment]
> > > You need to set current dark accent manually in `HKCU\Software\AccentColorizer` to yellow color from SVG files in `theme-dark` for now and it will work again without any issues
> > 
> > 
> > Sorry, but I didn't quite understand that. Wouldn't the glyphs remain yellow then?
> 
> ACE-11 actually just searches that SVG files for the color from the registry and replaces it to the current accent color. I.e. the color from the registry should match the color from the files. Sync it manually by modifying the registry key and it will work.

OK, will give it a shot in the morning and post results. Thank you.

**Comment by krilok** [comment]
So, tried changing the registry value a couple of times as instructed, but nothing happened and glyphs still remained yellow. Even tried setting different color hexes, but same results. So finally decided to undo everything and fully removed ACE-11, rebooted the computer, ran ACE-11 again, and it's now working...

Don't know what happened, but if it's working, I won't touch it any further... ;) 

Thank you anyhow for all the help.
