### ISSUE TITLE
Doesn't work on Windows 22635.4225

### ISSUE THREAD

**Issue by stiffbruno** [krlvm/AccentColorizer-E11#26]
I'm trying AccentColorizer-E11 v1.2.0.

**Comment by Crocodile73** [comment]
I don't think it works 100% anymore on the newer builds. For me i'm stuck with green accent, even when its not running. no idea why, When it does run it patches 2 icons on the right click menu and that is all.

**Comment by stiffbruno** [comment]
Haha, I'm in the same boat as you, stuck with the green highlight on all the glyphs in File Explorer and I haven't found any way to revert back to the default color at least.

**Comment by Crocodile73** [comment]
Only other option is to use startallback and use the Win 10 Ribbon Ui, it changes there colour only on that, tried awapping back to win 11, no joy. I don't want the ribbon ui, so for now, its green, lol

**Comment by prakharb5** [comment]
I'm on 22635.4515, and it is working perfectly for me.

**Comment by stiffbruno** [comment]
OK, I rolled back to main channel 23H2 (22631.4541) and It's fine.

**Comment by prakharb5** [comment]
I suppose you can close this issue then 🙂
