### ISSUE TITLE
Top icons (cut, copy...) not updated when changing accent color.

### ISSUE THREAD

**Issue by AestheticalZ** [krlvm/AccentColorizer-E11#8]
These icons don't get updated until you restart explorer, but the other icons update fine.
![image](https://user-images.githubusercontent.com/51166756/196463824-fb9315d9-322f-4f6d-b406-c999233099b6.png)

**Comment by krlvm** [comment]
I think they are cached by Explorer process, we can do anything about it without introducting some kind of hooking, infortunately.
